### ISSUE TITLE
Add example fixture

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#19]
## Description

A fixture in golang rust bun or bash should be showing an example usage of golang. 

## Tasks

- [x] Add in the example toml file
- [x] Add ts scripts using mocktimism with op-viem
- [x] Add ts setup to contributing docs
- [x] Add way of running fixtures to contribute docs
