### ISSUE TITLE
[P2] Add mocktimism specific rpc requests

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#25]
## Description

Anvil implemented hardhat rpc methods with `anvil_` rather than `hardhat_`.
- [Hardhat docs](https://hardhat.org/hardhat-network/docs/reference#hardhat-network-methods)
- [Anvil docs](https://book.getfoundry.sh/reference/anvil/)

This ticket is to add mocktimism specific rpc requests. these should be implemented in a decorator that intercepts the requests

## Tasks

Implement the following:
- [ ] Test for being able to set l1 base fee
- [ ] op_impersonate_[owner] Methods to impersonate privileged rollup actors
- [ ] op_stop_batches Stop batches from getting posted
- [ ] Anything that comes up as useful for op-viem tests setting up state
