### ISSUE TITLE
Add dockerfile for using mocktimism

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#27]
## Summary

Docker can both be the testing environment for CI and also a [distribution option of mocktimism](https://github.com/ethereum-optimism/mocktimism/issues/11). 

## Tasks

- [x] [Add dockerfile to that builds golang](https://github.com/ethereum-optimism/mocktimism/pull/41) similar to the [optimism monorepo](https://github.com/ethereum-optimism/optimism/blob/develop/indexer/Dockerfile)
- [x] [Dockerfile should be 2 stages](https://github.com/ethereum-optimism/mocktimism/pull/41) building the executable and then copying it
- [ ] Add a docker compose file for running it
- [ ] Make circleci run the tests in the dockerfile

**Comment by roninjin10** [comment]
Not necessary and likely better to use kurtosis
