### ISSUE TITLE
[Nice to have] Generate markdown docs about the cli from urfavecli

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#32]
## Description

We don't want to write docs for the cli we want to generate it in a script. It appears pretty easy to do looking at this https://github.com/urfave/cli/pull/830. We also want to make s

## Tasks

- [ ] Add a new `scripts/` package
- [ ] Add a script to generate markdown doc for cli app into docs/cli.md
- [ ] (optional) Add check to circleci config that make sure generated docs are up to date
