### ISSUE TITLE
Mocktimism config cli action should log config in toml form

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#33]
## Description

In #31 we added a cli command for logging the config. It logs it as a json but instead should log it as a toml by default and only as json if --json flag is passed in. This is similar to `forge config --help` command below

```
Options:
      --basic
          Print only a basic set of the currently set config values

      --json
          Print currently set config values as JSON

  -h, --help
          Print help (see a summary with '-h')
```

## tasks

- [ ] Move current config logic to only run if --json is passed in
- [ ] Make the default print it as a toml
- [ ] Add --help
- [ ] Add any additional tests

**Comment by Sabnock01** [comment]
I would like to take this one.
