### ISSUE TITLE
Document explicit usages of engine api in op-node

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#36]
## Description

To understand the changes to the engine API and also make sure we test all uses of it are compatible we should document the specific ways op-node interops with the engine api

Related to https://github.com/ethereum-optimism/mocktimism/issues/5

## Tasks

- [ ] Document a high level view
- [ ] Document links to code locations in op-node 
- [ ] Document which use cases feel like they could be left unimplemented if any
- [ ] Persist the docs in `docs/engine-api.md` as contributing docs and link to it in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] (optional) document links to reth

**Comment by roninjin10** [comment]
@anikaraghu @zencephalon and @roninjin10 to meet with @trianglesphere about this
- Being explored actively now so should have detailed answers
- Will to gather up a list of useful links before meeting

**Comment by trianglesphere** [comment]
OP Usage & Modifications: https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#engine-api

Paris Engine API: https://github.com/ethereum/execution-apis/blob/584905270d8ad665718058060267061ecfd79ca5/src/engine/paris.md

We use all but `engine_exchangeTransitionConfigurationV1`

Shanghai Engine API: https://github.com/ethereum/execution-apis/blob/584905270d8ad665718058060267061ecfd79ca5/src/engine/shanghai.md

In shanghai, we don't use the new APIs, but have updated to the V2 versions of the ones we use.

**Comment by roninjin10** [comment]
Added list of links including links @trianglesphere shared here: https://github.com/ethereum-optimism/mocktimism/issues/66
Also @anikaraghu @zencephalon and I are chatting with @trianglesphere soon about engine api
