### ISSUE TITLE
Add an initial README.md

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#58]
## Description

The repo currently has no README. Add any README that describes what Mocktimism is. Information is in this issue https://github.com/ethereum-optimism/mocktimism/issues/1

## Tasks
- [ ] Add a README.md
- [ ] Link to CONTRIBUTING.md
- [ ] Include that it alpha is under construction
- [ ] Add a short description of how mocktimism works

**Comment by ATREAY** [comment]
hey @roninjin10, can I work on this issue?

**Comment by roninjin10** [comment]
@ATREAY go for it ! Let me know if you got questions

**Comment by ATREAY** [comment]
Hey @roninjin10, I've got a quick question. When you mentioned that issue in the description, should I just add "what Mocktimism is" to the readme file, or should I include the whole text where that part is found?

**Comment by roninjin10** [comment]
@ATREAY should be a pretty short description of what mocktimism is. Feel free to leave a placeholder that I can fill in if it's not clear

**Comment by ATREAY** [comment]
Hey @roninjin10, I have created the readme file and included relevant information about Mocktimism. Please take a look whenever you can and let me know if any additional content should be included.
