### ISSUE TITLE
Add changesets to create changelogs

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#63]
## Description
Since mocktimism will initially be released in alpha and subject to breaking changes it is important that changlogs be kept for the npm and go packages. By using changesets with the github plugin release notes will be created in this github and the npm releases

https://github.com/changesets/changesets

## Tasks
- [ ] Add changesets folder https://github.com/ethereum-optimism/optimism/tree/develop/.changeset
- [ ] Add appropriate release version and changeset scripts to package.json https://github.com/ethereum-optimism/optimism/blob/develop/package.json#L30
- [ ] Add github action for releasing https://github.com/ethereum-optimism/optimism/blob/develop/.github/workflows/release.yml
- [ ] Add github action for releasing snapshots https://github.com/ethereum-optimism/optimism/blob/develop/.github/workflows/release-snapshot.yml

**Comment by roninjin10** [comment]
Not needed
