### ISSUE TITLE
[Nice to have] Add superchain repo 

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#79]
## Description

In https://github.com/ethereum-optimism/mocktimism/pull/78 we added support for l2BlockNumber via l2Oracle. We should get the l2Oracle address from the [superchain registry](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/goerli/superchain.yaml) instead

## Tasks

- [ ] Add superchain registry (instructions in [readme](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/goerli/superchain.yaml)
- [ ] Use it to look up the oracle address
- [ ] Also add oracle address as an option to l1 chains
